language: python
python:
    - 3.5
    - 3.6
    - 3.6-dev
    - 3.7-dev
    - 3.7
    - 3.8
install:
  - python3 -m pip install -U git+git://github.com/python/mypy.git
  - pip install -e .
script: python setup.py test

# use unsupported xenial
dist: xenial
sudo: required
